%%% ==================================================================
%%% this file is generated by tools.
%%% ==================================================================

%%  location
-record(location, {
          region = "" :: string(),
          country = "" :: string()
         }).

%%  test
-record(person, {
          name = "" :: string(),
          address = "" :: string(),
          phone_number = "" :: string(),
          groups = [] :: list(),
          age = 0 :: integer(),
          location = #location{} :: #location{}
         }).

