%%% ==================================================================
%%% this file is generated by tools. do not edit it by yourself.
%%% ==================================================================

-module(protocal_encoder).
-compile(export_all).
-include("record.hrl").

-include("api.hrl").

-include("error.hrl").

-include("define.hrl").

encode(_, _) ->
  error.

