%%% ==================================================================
%%%  this file is generated by tools. do not edit it by yourself.
%%% ==================================================================

-module(protocal_decoder).
-compile(export_all).
-include("record.hrl").

-include("api.hrl").

-include("error.hrl").

decode(Type, _Data)  ->
  io:format("unkown type:~p\n",[Type]),
  null.

