%%% ==================================================================
%%% this file is generated by tools
%%% ==================================================================

%% location
encode_location(Location = #location{} ) ->
  RegionBin = encode_string(Location#location.region),
  CountryBin = encode_string(Location#location.country),
  list_to_binary([RegionBin, CountryBin]).

decode_location(<<Data/binary>>) ->
  {Region, RegionDataLeft} = decode_string(Data),
  {Country, CountryDataLeft} = decode_string(RegionDataLeft),
  Location=  #location{region = Region, country = Country},
  {Location, CountryDataLeft}.

%% person
encode_person(Person = #person{} ) ->
  NameBin = encode_string(Person#person.name),
  AddressBin = encode_string(Person#person.address),
  Phone_numberBin = encode_string(Person#person.phone_number),
  GroupsBin = encode_array(Person#person.groups, encode_string),
  AgeBin = encode_integer(Person#person.age),
  LocationBin = encode_location(Person#person.location),
  list_to_binary([NameBin, AddressBin, Phone_numberBin, GroupsBin, AgeBin, LocationBin]).

decode_person(<<Data/binary>>) ->
  {Name, NameDataLeft} = decode_string(Data),
  {Address, AddressDataLeft} = decode_string(NameDataLeft),
  {Phone_number, Phone_numberDataLeft} = decode_string(AddressDataLeft),
  {Groups, GroupsDataLeft} = decode_array(Phone_numberDataLeft,decode_string),
  {Age, AgeDataLeft} = decode_integer(GroupsDataLeft),
  {Location, LocationDataLeft} = decode_location(AgeDataLeft),
  Person=  #person{name = Name, address = Address, phone_number = Phone_number, groups = Groups, age = Age, location = Location},
  {Person, LocationDataLeft}.

