%%
%% Autogenerated by Thrift Compiler (0.9.2)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(simple_types).

-include("simple_types.hrl").

-export([struct_info/1, struct_info_ext/1]).

struct_info('location') ->
  {struct, [{1, string},
          {2, string}]}
;

struct_info('person') ->
  {struct, [{1, string},
          {2, string},
          {3, string},
          {4, {list, string}},
          {5, i32},
          {6, {struct, {'simple_types', 'location'}}}]}
;

struct_info('i am a dummy struct') -> undefined.

struct_info_ext('location') ->
  {struct, [{1, undefined, string, 'region', undefined},
          {2, undefined, string, 'country', undefined}]}
;

struct_info_ext('person') ->
  {struct, [{1, undefined, string, 'name', undefined},
          {2, undefined, string, 'address', undefined},
          {3, undefined, string, 'phone_number', undefined},
          {4, undefined, {list, string}, 'groups', []},
          {5, undefined, i32, 'age', undefined},
          {6, undefined, {struct, {'simple_types', 'location'}}, 'location', #location{}}]}
;

struct_info_ext('i am a dummy struct') -> undefined.

